// AUTO-GENERATED from the Elixir Project Estimation Template V2 (.xlsx).
// Regenerate via scripts in the session that extracted this if the source workbook changes.
// NOTE: fixes a real bug in the source spreadsheet where several tabs' "Setup" rows
// looked up the PREVIOUS row's complexity dropdown instead of their own (off-by-one
// copy-paste error in Sales/CMS/DealHub/HS Deployment & Go-Live tabs). Here every line
// item always uses its own complexity selection, as originally intended.

import type {
  StandardWorkstream,
  ThirdPartyIntegrationState,
  ElixirSyncIntegrationState,
  EstimationState,
} from './types';
import { createDefaultHubSpotLicenseState } from './hubspotPricing';

export const STANDARD_WORKSTREAM_TEMPLATES: StandardWorkstream[] = [
  {
    key: "business_assessment",
    label: { en: "Business Assessment", nl: "Business Assessment" },
    enabled: true,
    hourlyRate: 150,
    items: [
      {
        id: "business_assessment-1-strategy-interview",
        activity: "Session",
        topic: { en: "Strategy Interview", nl: "Strategie-interview" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: { en: "Interview + write-up; input is translated into recommendations for the solution design.", nl: "Interview + uitwerking; input wordt vertaald naar aanbevelingen voor het solution design." },
        enabled: true,
      },
      {
        id: "business_assessment-2-marketing-interview",
        activity: "Session",
        topic: { en: "Marketing Interview", nl: "Marketing-interview" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: { en: "Interview + write-up; input is translated into recommendations for the solution design.", nl: "Interview + uitwerking; input wordt vertaald naar aanbevelingen voor het solution design." },
        enabled: true,
      },
      {
        id: "business_assessment-3-sales-interview",
        activity: "Session",
        topic: { en: "Sales Interview", nl: "Sales-interview" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: { en: "Interview + write-up; input is translated into recommendations for the solution design.", nl: "Interview + uitwerking; input wordt vertaald naar aanbevelingen voor het solution design." },
        enabled: true,
      },
      {
        id: "business_assessment-4-service-interview",
        activity: "Session",
        topic: { en: "Service Interview", nl: "Service-interview" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: { en: "Interview + write-up; input is translated into recommendations for the solution design.", nl: "Interview + uitwerking; input wordt vertaald naar aanbevelingen voor het solution design." },
        enabled: true,
      },
      {
        id: "business_assessment-5-datait-interview-reverse-demo",
        activity: "Session",
        topic: { en: "Data/IT Interview - Reverse demo", nl: "Data/IT-interview - Reverse demo" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: { en: "Interview + write-up; input is translated into recommendations for the solution design.", nl: "Interview + uitwerking; input wordt vertaald naar aanbevelingen voor het solution design." },
        enabled: true,
      },
      {
        id: "business_assessment-6-solution-design-workshop",
        activity: "Session",
        topic: { en: "Solution design workshop", nl: "Solution design-workshop" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: { en: "Only for uni-dimensional projects", nl: "Alleen voor uni-dimensionale projecten" },
        enabled: true,
      },
      {
        id: "business_assessment-7-assessment-presentation",
        activity: "Session",
        topic: { en: "Assessment presentation", nl: "Assessment-presentatie" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: { en: "Only for multi dimensional projects", nl: "Alleen voor multidimensionale projecten" },
        enabled: true,
      },
      {
        id: "business_assessment-8-create-solution-design-user-stories",
        activity: "Desk work",
        topic: { en: "Create solution design & user stories", nl: "Solution design & user stories opstellen" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: { en: "Only for uni-dimensional projects", nl: "Alleen voor uni-dimensionale projecten" },
        enabled: true,
      },
      {
        id: "business_assessment-9-prepare-assessment-presentation",
        activity: "Desk work",
        topic: { en: "Prepare assessment presentation", nl: "Assessment-presentatie voorbereiden" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: { en: "Only for multi dimensional projects", nl: "Alleen voor multidimensionale projecten" },
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -1.0, comment: { en: "1,5 hr Session with 2 people, no preparation time", nl: "1,5 uur sessie met 2 personen, geen voorbereidingstijd" } },
    "Standard": { hours: 0.0, comment: { en: "1,5 hr Session with 2 people, normal preparation time", nl: "1,5 uur sessie met 2 personen, normale voorbereidingstijd" } },
    "Medium": { hours: 1.0, comment: { en: "2 hr Session with 2 people, medium complexity and medium preparation time", nl: "2 uur sessie met 2 personen, gemiddelde complexiteit en gemiddelde voorbereidingstijd" } },
    "High": { hours: 2.0, comment: { en: "2 hr Session with 2 people, high complexity and high preparation time", nl: "2 uur sessie met 2 personen, hoge complexiteit en hoge voorbereidingstijd" } },
  },
    setupComplexity: {
    "Low": { hours: -1.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 1.0, comment: null },
    "High": { hours: 2.0, comment: null },
  },
  },
  {
    key: "technical_assessment",
    label: { en: "Technical Assessment", nl: "Technical Assessment" },
    enabled: true,
    hourlyRate: 150,
    items: [
      {
        id: "technical_assessment-1-understanding-situation-processes",
        activity: "Session",
        topic: { en: "Understanding situation & processes", nl: "Situatie & processen in kaart brengen" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "technical_assessment-2-best-practice-integration-flow",
        activity: "Session",
        topic: { en: "Best-practice integration flow", nl: "Best-practice integratieflow" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "technical_assessment-3-adapted-integration-flow",
        activity: "Session",
        topic: { en: "Adapted integration flow", nl: "Aangepaste integratieflow" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "technical_assessment-4-data-mapping-i",
        activity: "Session",
        topic: { en: "Data mapping I", nl: "Datamapping I" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "technical_assessment-5-functional-requirements",
        activity: "Session",
        topic: { en: "Functional Requirements", nl: "Functionele requirements" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "technical_assessment-6-integration-flow-definition",
        activity: "Setup",
        topic: { en: "Integration Flow Definition", nl: "Integratieflow definiëren" },
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "technical_assessment-7-mapping-file",
        activity: "Setup",
        topic: { en: "Mapping File", nl: "Mappingbestand" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "technical_assessment-8-functional-requirements-document",
        activity: "Setup",
        topic: { en: "Functional Requirements Document", nl: "Functioneel requirements-document" },
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: { en: "1,5 hr Session with 2 people, no preparation time", nl: "1,5 uur sessie met 2 personen, geen voorbereidingstijd" } },
    "Standard": { hours: 0.0, comment: { en: "1,5 hr Session with 2 people, normal preparation time", nl: "1,5 uur sessie met 2 personen, normale voorbereidingstijd" } },
    "Medium": { hours: 2.0, comment: { en: "2 hr Session with 2 people, medium complexity and medium preparation time", nl: "2 uur sessie met 2 personen, gemiddelde complexiteit en gemiddelde voorbereidingstijd" } },
    "High": { hours: 4.0, comment: { en: "2 hr Session with 2 people, high complexity and high preparation time", nl: "2 uur sessie met 2 personen, hoge complexiteit en hoge voorbereidingstijd" } },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
  {
    key: "data_migration",
    label: { en: "Data Migration", nl: "Datamigratie" },
    enabled: true,
    hourlyRate: 150,
    items: [
      {
        id: "data_migration-1-kick-off-hs-best-practices-customer-inpu",
        activity: "Session",
        topic: { en: "Kick-off - HS Best Practices & Customer Input", nl: "Kick-off - HubSpot best practices & klantinput" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-2-data-mapping-i",
        activity: "Session",
        topic: { en: "Data Mapping I", nl: "Datamapping I" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-3-data-mapping-ii",
        activity: "Session",
        topic: { en: "Data Mapping II", nl: "Datamapping II" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-4-alignment-before-loading-in-test",
        activity: "Session",
        topic: { en: "Alignment before loading in Test", nl: "Afstemming vóór laden in Test" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-5-data-validation-in-test",
        activity: "Session",
        topic: { en: "Data Validation in Test", nl: "Datavalidatie in Test" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-6-alignment-before-loading-in-production",
        activity: "Session",
        topic: { en: "Alignment before loading in Production", nl: "Afstemming vóór laden in Productie" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-7-data-validation-in-prod",
        activity: "Session",
        topic: { en: "Data Validation in Prod", nl: "Datavalidatie in Productie" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-8-data-transformation",
        activity: "Setup",
        topic: { en: "Data Transformation", nl: "Datatransformatie" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-9-data-loading-in-test",
        activity: "Setup",
        topic: { en: "Data Loading in Test", nl: "Data laden in Test" },
        standardEffort: 6.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-10-data-loading-in-prod",
        activity: "Setup",
        topic: { en: "Data Loading in Prod", nl: "Data laden in Productie" },
        standardEffort: 6.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: { en: "1,5 hr Session with 2 people, no preparation time", nl: "1,5 uur sessie met 2 personen, geen voorbereidingstijd" } },
    "Standard": { hours: 0.0, comment: { en: "1,5 hr Session with 2 people, normal preparation time", nl: "1,5 uur sessie met 2 personen, normale voorbereidingstijd" } },
    "Medium": { hours: 2.0, comment: { en: "1,5 hr Session with 2 people, medium complexity and medium preparation time", nl: "1,5 uur sessie met 2 personen, gemiddelde complexiteit en gemiddelde voorbereidingstijd" } },
    "High": { hours: 4.0, comment: { en: "1,5 hr Session with 2 people, high complexity and high preparation time", nl: "1,5 uur sessie met 2 personen, hoge complexiteit en hoge voorbereidingstijd" } },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
  {
    key: "sales_implementation",
    label: { en: "Sales Implementation", nl: "Sales-implementatie" },
    enabled: true,
    hourlyRate: 135,
    items: [
      {
        id: "sales_implementation-1-sales-kick-off-workshop",
        activity: "Session",
        topic: { en: "Sales Kick-off Workshop", nl: "Sales kick-off workshop" },
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-2-company-contact-lead-activity-mgmt",
        activity: "Session",
        topic: { en: "Company & Contact, lead & activity Mgmt", nl: "Bedrijven & contacten, lead- en activiteitenbeheer" },
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-3-deal-pipeline-management",
        activity: "Session",
        topic: { en: "Deal & Pipeline management", nl: "Deal- en pipelinebeheer" },
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-4-quote-management",
        activity: "Session",
        topic: { en: "Quote management", nl: "Offertebeheer" },
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-5-sales-reporting-authorizations",
        activity: "Session",
        topic: { en: "Sales Reporting & Authorizations", nl: "Sales-rapportage & autorisaties" },
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-6-setup-checkin-session-i",
        activity: "Session",
        topic: { en: "Setup Checkin Session I", nl: "Setup check-in sessie I" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-7-setup-checkin-session-ii",
        activity: "Session",
        topic: { en: "Setup Checkin Session II", nl: "Setup check-in sessie II" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-8-final-checkin-session-before-go-live",
        activity: "Session",
        topic: { en: "Final Checkin Session (before Go-Live)", nl: "Laatste check-in sessie (vóór Go-Live)" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-9-sales-marketing-alignment",
        activity: "Session",
        topic: { en: "Sales & marketing alignment", nl: "Sales- en marketingafstemming" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-10-companies",
        activity: "Setup",
        topic: { en: "Companies", nl: "Bedrijven" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-11-contacts",
        activity: "Setup",
        topic: { en: "Contacts", nl: "Contacten" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-12-lead-management",
        activity: "Setup",
        topic: { en: "Lead management", nl: "Leadbeheer" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-13-deals",
        activity: "Setup",
        topic: { en: "Deals", nl: "Deals" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-14-quoting",
        activity: "Setup",
        topic: { en: "Quoting", nl: "Offertes" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-15-dashboards-reports",
        activity: "Setup",
        topic: { en: "Dashboards & reports", nl: "Dashboards & rapportages" },
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-16-users-teams-permission-sets",
        activity: "Setup",
        topic: { en: "Users, Teams & Permission sets", nl: "Gebruikers, teams & permissiesets" },
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: { en: "1,5 hr Session with 2 people, no preparation time", nl: "1,5 uur sessie met 2 personen, geen voorbereidingstijd" } },
    "Standard": { hours: 0.0, comment: { en: "3 hr Session with 2 people, normal preparation time", nl: "3 uur sessie met 2 personen, normale voorbereidingstijd" } },
    "Medium": { hours: 2.0, comment: { en: "3 hr Session with 2 people, medium complexity and medium preparation time", nl: "3 uur sessie met 2 personen, gemiddelde complexiteit en gemiddelde voorbereidingstijd" } },
    "High": { hours: 4.0, comment: { en: "3 hr Session with 2 people, high complexity and high preparation time", nl: "3 uur sessie met 2 personen, hoge complexiteit en hoge voorbereidingstijd" } },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
  {
    key: "service_implementation",
    label: { en: "Service Implementation", nl: "Service-implementatie" },
    enabled: true,
    hourlyRate: 135,
    items: [
      {
        id: "service_implementation-1-service-kick-off-workshop",
        activity: "Session",
        topic: { en: "Service kick-off Workshop", nl: "Service kick-off workshop" },
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-2-company-contact-management",
        activity: "Session",
        topic: { en: "Company & contact management", nl: "Bedrijven- & contactenbeheer" },
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-3-ticket-management",
        activity: "Session",
        topic: { en: "Ticket management", nl: "Ticketbeheer" },
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-4-knowledge-base-feedback-surveys",
        activity: "Session",
        topic: { en: "Knowledge base & feedback surveys", nl: "Kennisbank & feedback-enquêtes" },
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-5-service-reporting-authorizations",
        activity: "Session",
        topic: { en: "Service reporting & Authorizations", nl: "Service-rapportage & autorisaties" },
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-6-setup-checkin-session-i",
        activity: "Session",
        topic: { en: "Setup Checkin Session I", nl: "Setup check-in sessie I" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-7-setup-checkin-session-ii",
        activity: "Session",
        topic: { en: "Setup Checkin Session II", nl: "Setup check-in sessie II" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-8-final-wrap-up-before-training",
        activity: "Session",
        topic: { en: "Final wrap-up (before training)", nl: "Laatste afronding (vóór training)" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-9-companies",
        activity: "Setup",
        topic: { en: "Companies", nl: "Bedrijven" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-10-contacts",
        activity: "Setup",
        topic: { en: "Contacts", nl: "Contacten" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-11-tickets",
        activity: "Setup",
        topic: { en: "Tickets", nl: "Tickets" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-12-customer-portal",
        activity: "Setup",
        topic: { en: "Customer portal", nl: "Klantportaal" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-13-knowledge-base",
        activity: "Setup",
        topic: { en: "Knowledge base", nl: "Kennisbank" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-14-surveys",
        activity: "Setup",
        topic: { en: "Surveys", nl: "Enquêtes" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-15-dashboards-reports",
        activity: "Setup",
        topic: { en: "Dashboards & reports", nl: "Dashboards & rapportages" },
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-16-users-teams-permission-sets",
        activity: "Setup",
        topic: { en: "Users, Teams & Permission sets", nl: "Gebruikers, teams & permissiesets" },
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: { en: "1,5 hr Session with 2 people, no preparation time", nl: "1,5 uur sessie met 2 personen, geen voorbereidingstijd" } },
    "Standard": { hours: 0.0, comment: { en: "3 hr Session with 2 people, normal preparation time", nl: "3 uur sessie met 2 personen, normale voorbereidingstijd" } },
    "Medium": { hours: 2.0, comment: { en: "3 hr Session with 2 people, medium complexity and medium preparation time", nl: "3 uur sessie met 2 personen, gemiddelde complexiteit en gemiddelde voorbereidingstijd" } },
    "High": { hours: 4.0, comment: { en: "3 hr Session with 2 people, high complexity and high preparation time", nl: "3 uur sessie met 2 personen, hoge complexiteit en hoge voorbereidingstijd" } },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
  {
    key: "marketing_implementation",
    label: { en: "Marketing Implementation", nl: "Marketing-implementatie" },
    enabled: true,
    hourlyRate: 135,
    items: [
      {
        id: "marketing_implementation-1-marketing-kick-off-tech-questionnaire",
        activity: "Session",
        topic: { en: "Marketing Kick-off (Tech Questionnaire)", nl: "Marketing kick-off (technische vragenlijst)" },
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-2-gdpr-marketing-contacts",
        activity: "Session",
        topic: { en: "GDPR & marketing contacts", nl: "AVG & marketingcontacten" },
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-3-campaign-definition-technical-set-up",
        activity: "Session",
        topic: { en: "Campaign Definition, Technical set-up", nl: "Campagnedefinitie, technische set-up" },
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-4-buyer-personas-buyers-journey",
        activity: "Session",
        topic: { en: "Buyer Personas & Buyers Journey", nl: "Buyer persona's & buyer journey" },
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-5-lead-qualification-scoring-campaign-flow",
        activity: "Session",
        topic: { en: "Lead qualification / scoring & Campaign Flow", nl: "Leadkwalificatie / scoring & campagneflow" },
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-6-assets-training-i",
        activity: "Session",
        topic: { en: "Assets Training I", nl: "Training materialen I" },
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-7-assets-training-ii",
        activity: "Session",
        topic: { en: "Assets Training II", nl: "Training materialen II" },
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-8-campaign-go-live",
        activity: "Session",
        topic: { en: "Campaign go-live", nl: "Campagne go-live" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-9-marketing-reporting-analytics",
        activity: "Session",
        topic: { en: "Marketing reporting & analytics", nl: "Marketingrapportage & analyse" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-10-setup-checkin-session-i",
        activity: "Session",
        topic: { en: "Setup Checkin Session I", nl: "Setup check-in sessie I" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-11-setup-checkin-session-ii",
        activity: "Session",
        topic: { en: "Setup Checkin Session II", nl: "Setup check-in sessie II" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-12-campaign-follow-up",
        activity: "Session",
        topic: { en: "Campaign Follow-up ", nl: "Campagne follow-up" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-13-general-set-up-tracking-link-domains-sub",
        activity: "Setup",
        topic: { en: "General set-up: Tracking link, Domains, Subdomains, Compliance, Plug&Play Integrations", nl: "Algemene set-up: tracking link, domeinen, subdomeinen, compliance, plug&play-integraties" },
        standardEffort: 6.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-14-gdpr-set-up-consent-subscription-types-c",
        activity: "Setup",
        topic: { en: "GDPR set-up: Consent, subscription types, cookie banner, DOI, marketing contacts", nl: "AVG-set-up: toestemming, abonnementstypen, cookiebanner, DOI, marketingcontacten" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-15-lead-qualification-scoring",
        activity: "Setup",
        topic: { en: "Lead Qualification / Scoring", nl: "Leadkwalificatie / scoring" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-16-campaign-assets-ads-social-landing-pages",
        activity: "Setup",
        topic: { en: "Campaign assets: Ads, Social, Landing pages, Forms, Mails, Workflows", nl: "Campagnemateriaal: advertenties, social, landingspagina's, formulieren, mails, workflows" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-17-dashboards-reports",
        activity: "Setup",
        topic: { en: "Dashboards & reports", nl: "Dashboards & rapportages" },
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-18-users-teams-permission-sets",
        activity: "Setup",
        topic: { en: "Users, Teams & Permission sets", nl: "Gebruikers, teams & permissiesets" },
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: { en: "1,5 hr Session with 2 people, no preparation time", nl: "1,5 uur sessie met 2 personen, geen voorbereidingstijd" } },
    "Standard": { hours: 0.0, comment: { en: "1,5 hr Session with 2 people, normal preparation time", nl: "1,5 uur sessie met 2 personen, normale voorbereidingstijd" } },
    "Medium": { hours: 2.0, comment: { en: "1,5 hr Session with 2 people, medium complexity and medium preparation time", nl: "1,5 uur sessie met 2 personen, gemiddelde complexiteit en gemiddelde voorbereidingstijd" } },
    "High": { hours: 4.0, comment: { en: "1,5 hr Session with 2 people, high complexity and high preparation time", nl: "1,5 uur sessie met 2 personen, hoge complexiteit en hoge voorbereidingstijd" } },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
  {
    key: "cms_implementation",
    label: { en: "CMS Implementation", nl: "CMS-implementatie" },
    enabled: true,
    hourlyRate: 135,
    items: [
      {
        id: "cms_implementation-1-cms-kick-off-approach",
        activity: "Session",
        topic: { en: "CMS Kick-off / Approach", nl: "CMS kick-off / aanpak" },
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-2-setup-future-branding",
        activity: "Session",
        topic: { en: "Setup & future Branding", nl: "Setup & toekomstige branding" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-3-page-template-review",
        activity: "Session",
        topic: { en: "Page Template Review", nl: "Review paginatemplates" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-4-cms-training-i",
        activity: "Session",
        topic: { en: "CMS Training I", nl: "CMS-training I" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-5-cms-training-ii",
        activity: "Session",
        topic: { en: "CMS Training II", nl: "CMS-training II" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-6-migration-session-i",
        activity: "Session",
        topic: { en: "Migration Session I", nl: "Migratiesessie I" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-7-migration-session-ii",
        activity: "Session",
        topic: { en: "Migration Session II", nl: "Migratiesessie II" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-8-setup-checkin-fine-tuning-alignment-i",
        activity: "Session",
        topic: { en: "Setup Checkin & Fine Tuning Alignment I", nl: "Setup check-in & fine-tuning afstemming I" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-9-setup-checkin-fine-tuning-alignment-ii",
        activity: "Session",
        topic: { en: "Setup Checkin & Fine Tuning Alignment II", nl: "Setup check-in & fine-tuning afstemming II" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-10-setup-branding",
        activity: "Setup",
        topic: { en: "Setup & Branding", nl: "Setup & branding" },
        standardEffort: 8.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-11-page-templates-modules",
        activity: "Setup",
        topic: { en: "Page Templates & Modules", nl: "Paginatemplates & modules" },
        standardEffort: 12.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-12-fine-tuning-after-feedback",
        activity: "Setup",
        topic: { en: "Fine Tuning after Feedback", nl: "Fine-tuning na feedback" },
        standardEffort: 8.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-13-redirect-setup",
        activity: "Setup",
        topic: { en: "Redirect Setup", nl: "Redirect-setup" },
        standardEffort: 8.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-14-migration-support",
        activity: "Setup",
        topic: { en: "Migration Support", nl: "Migratieondersteuning" },
        standardEffort: 16.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-15-users-teams-permission-sets",
        activity: "Setup",
        topic: { en: "Users, Teams & Permission sets", nl: "Gebruikers, teams & permissiesets" },
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: { en: "1,5 hr Session with 2 people, no preparation time", nl: "1,5 uur sessie met 2 personen, geen voorbereidingstijd" } },
    "Standard": { hours: 0.0, comment: { en: "1,5 hr Session with 2 people, normal preparation time", nl: "1,5 uur sessie met 2 personen, normale voorbereidingstijd" } },
    "Medium": { hours: 2.0, comment: { en: "1,5 hr Session with 2 people, medium complexity and medium preparation time", nl: "1,5 uur sessie met 2 personen, gemiddelde complexiteit en gemiddelde voorbereidingstijd" } },
    "High": { hours: 4.0, comment: { en: "1,5 hr Session with 2 people, high complexity and high preparation time", nl: "1,5 uur sessie met 2 personen, hoge complexiteit en hoge voorbereidingstijd" } },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
  {
    key: "dealhub_implementation",
    label: { en: "DealHub Implementation", nl: "DealHub-implementatie" },
    enabled: true,
    hourlyRate: 135,
    items: [
      {
        id: "dealhub_implementation-1-cpq-kick-off-approach",
        activity: "Session",
        topic: { en: "CPQ Kick-off / Approach", nl: "CPQ kick-off / aanpak" },
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-2-setup-analysis-reverse-demo",
        activity: "Session",
        topic: { en: "Setup Analysis, Reverse Demo", nl: "Setupanalyse, reverse demo" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-3-playbook-setup",
        activity: "Session",
        topic: { en: "Playbook Setup", nl: "Playbook-setup" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-4-product-setup",
        activity: "Session",
        topic: { en: "Product Setup", nl: "Productsetup" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-5-pricing-discount-setup",
        activity: "Session",
        topic: { en: "Pricing & Discount Setup", nl: "Prijs- & kortingsetup" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-6-pricing-discount-rule-setup",
        activity: "Session",
        topic: { en: "Pricing & Discount Rule Setup", nl: "Prijs- & kortingsregel-setup" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-7-data-migration-alignment",
        activity: "Session",
        topic: { en: "Data Migration Alignment", nl: "Afstemming datamigratie" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-8-dealroom-setup",
        activity: "Session",
        topic: { en: "DealRoom Setup", nl: "DealRoom-setup" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-9-setup-checkin-session-i",
        activity: "Session",
        topic: { en: "Setup Checkin Session I", nl: "Setup check-in sessie I" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-10-setup-checkin-session-ii",
        activity: "Session",
        topic: { en: "Setup Checkin Session II", nl: "Setup check-in sessie II" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-11-final-wrap-up-before-training",
        activity: "Session",
        topic: { en: "Final wrap-up (before training)", nl: "Laatste afronding (vóór training)" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-12-playbook-setup",
        activity: "Setup",
        topic: { en: "Playbook Setup", nl: "Playbook-setup" },
        standardEffort: 8.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-13-product-setup",
        activity: "Setup",
        topic: { en: "Product Setup", nl: "Productsetup" },
        standardEffort: 12.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-14-pricing-discount-setup",
        activity: "Setup",
        topic: { en: "Pricing & Discount Setup", nl: "Prijs- & kortingsetup" },
        standardEffort: 8.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-15-pricing-discount-rule-setup",
        activity: "Setup",
        topic: { en: "Pricing & Discount Rule Setup", nl: "Prijs- & kortingsregel-setup" },
        standardEffort: 8.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-16-data-migration-alignment",
        activity: "Setup",
        topic: { en: "Data Migration Alignment", nl: "Afstemming datamigratie" },
        standardEffort: 16.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-17-dealroom",
        activity: "Setup",
        topic: { en: "DealRoom", nl: "DealRoom" },
        standardEffort: 8.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-18-fine-tuning-rework",
        activity: "Setup",
        topic: { en: "Fine Tuning, Rework", nl: "Fine-tuning, revisie" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: { en: "1,5 hr Session with 2 people, no preparation time", nl: "1,5 uur sessie met 2 personen, geen voorbereidingstijd" } },
    "Standard": { hours: 0.0, comment: { en: "3 hr Session with 2 people, normal preparation time", nl: "3 uur sessie met 2 personen, normale voorbereidingstijd" } },
    "Medium": { hours: 2.0, comment: { en: "3 hr Session with 2 people, medium complexity and medium preparation time", nl: "3 uur sessie met 2 personen, gemiddelde complexiteit en gemiddelde voorbereidingstijd" } },
    "High": { hours: 4.0, comment: { en: "3 hr Session with 2 people, high complexity and high preparation time", nl: "3 uur sessie met 2 personen, hoge complexiteit en hoge voorbereidingstijd" } },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
  {
    key: "deployment_golive",
    label: { en: "HubSpot Deployment & Go-Live", nl: "HubSpot Deployment & Go-Live" },
    enabled: true,
    hourlyRate: 135,
    items: [
      {
        id: "deployment_golive-1-sales-key-user-training",
        activity: "Session",
        topic: { en: "Sales key user training", nl: "Sales key-user training" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-2-service-key-user-training",
        activity: "Session",
        topic: { en: "Service key user training", nl: "Service key-user training" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-3-marketing-key-user-training",
        activity: "Session",
        topic: { en: "Marketing key user training", nl: "Marketing key-user training" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-4-super-admin-training",
        activity: "Session",
        topic: { en: "Super Admin training", nl: "Super Admin-training" },
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-5-sales-end-user-training-6-8-users-sessio",
        activity: "Session",
        topic: { en: "Sales end user training (6-8 users / session)", nl: "Sales eindgebruikerstraining (6-8 gebruikers / sessie)" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-6-service-end-user-training-6-8-users-sess",
        activity: "Session",
        topic: { en: "Service end user training (6-8 users / session)", nl: "Service eindgebruikerstraining (6-8 gebruikers / sessie)" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-7-marketing-end-user-training-6-8-users-se",
        activity: "Session",
        topic: { en: "Marketing end user training (6-8 users / session)", nl: "Marketing eindgebruikerstraining (6-8 gebruikers / sessie)" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-8-hypercare-support",
        activity: "Session",
        topic: { en: "Hypercare Support", nl: "Hypercare-ondersteuning" },
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-9-deployment-sales-prod",
        activity: "Setup",
        topic: { en: "Deployment Sales Prod", nl: "Deployment Sales Productie" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-10-deployment-service-prod",
        activity: "Setup",
        topic: { en: "Deployment Service Prod", nl: "Deployment Service Productie" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-11-deployment-marketing-prod",
        activity: "Setup",
        topic: { en: "Deployment Marketing Prod", nl: "Deployment Marketing Productie" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-12-setup-hypercare",
        activity: "Setup",
        topic: { en: "Setup Hypercare", nl: "Setup hypercare" },
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: { en: "1 Session, one consultant, no preperation time", nl: "1 sessie, één consultant, geen voorbereidingstijd" } },
    "Standard": { hours: 0.0, comment: { en: "1 Session, one consultant, normal preperation time", nl: "1 sessie, één consultant, normale voorbereidingstijd" } },
    "Medium": { hours: 2.0, comment: { en: "1 Session, one consultant, medium preperation time", nl: "1 sessie, één consultant, gemiddelde voorbereidingstijd" } },
    "High": { hours: 4.0, comment: { en: "1 Session, one consultant, high preperation time", nl: "1 sessie, één consultant, hoge voorbereidingstijd" } },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
];

export const THIRD_PARTY_INTEGRATION_TEMPLATE: ThirdPartyIntegrationState = {
  enabled: false,
  hourlyRate: 150,
  items: [
    {
      id: "tp-1-lead",
      activity: "Setup",
      topic: { en: "Lead", nl: "Lead" },
      from: "Hubspot",
      to: "ERP",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-2-lead",
      activity: "Setup",
      topic: { en: "Lead", nl: "Lead" },
      from: "ERP",
      to: "Hubspot",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-3-contact",
      activity: "Setup",
      topic: { en: "Contact", nl: "Contact" },
      from: "Hubspot",
      to: "ERP",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-4-contact",
      activity: "Setup",
      topic: { en: "Contact", nl: "Contact" },
      from: "ERP",
      to: "Hubspot",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-5-company",
      activity: "Setup",
      topic: { en: "Company", nl: "Bedrijf" },
      from: "Hubspot",
      to: "ERP",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-6-company",
      activity: "Setup",
      topic: { en: "Company", nl: "Bedrijf" },
      from: "ERP",
      to: "Hubspot",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-7-deal",
      activity: "Setup",
      topic: { en: "Deal", nl: "Deal" },
      from: "ERP",
      to: "Hubspot",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-8-deal-line-item",
      activity: "Setup",
      topic: { en: "Deal Line Item", nl: "Deal line item" },
      from: "ERP",
      to: "Hubspot",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-9-order",
      activity: "Setup",
      topic: { en: "Order ", nl: "Order" },
      from: "ERP",
      to: "Hubspot",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-10-order-line-item",
      activity: "Setup",
      topic: { en: "Order Line Item", nl: "Order line item" },
      from: "ERP",
      to: "Hubspot",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-11-custom-object",
      activity: "Setup",
      topic: { en: "Custom Object", nl: "Custom object" },
      from: "Hubspot",
      to: "ERP",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-12-prod-deployment",
      activity: "Setup",
      topic: { en: "Prod Deployment", nl: "Productie-deployment" },
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-13-hypercare",
      activity: "Setup",
      topic: { en: "Hypercare", nl: "Hypercare" },
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-14-kick-off-session",
      activity: "Session",
      topic: { en: "Kick-Off Session", nl: "Kick-off sessie" },
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-15-setup-checkin-session-i",
      activity: "Session",
      topic: { en: "Setup Checkin Session I", nl: "Setup check-in sessie I" },
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-16-setup-checkin-session-ii",
      activity: "Session",
      topic: { en: "Setup Checkin Session II", nl: "Setup check-in sessie II" },
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-17-setup-checkin-session-iii",
      activity: "Session",
      topic: { en: "Setup Checkin Session III", nl: "Setup check-in sessie III" },
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-18-pm-checkins",
      activity: "Session",
      topic: { en: "PM Checkins", nl: "PM check-ins" },
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-19-external-testing-uat",
      activity: "Session",
      topic: { en: "External Testing (UAT)", nl: "Externe testen (UAT)" },
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-20-internal-testing-uat",
      activity: "Session",
      topic: { en: "Internal Testing (UAT)", nl: "Interne testen (UAT)" },
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
  ],
  sessionComplexity: {
    "High complexity": { hours: 12.0, comment: { en: "High requirements, unknown integration flows, unknown technical setup, high risk of issues", nl: "Hoge eisen, onbekende integratieflows, onbekende technische setup, hoog risico op problemen" } },
    "Medium complexity": { hours: 8.0, comment: { en: "Medium requirements, partly known integration flows and partly technical setup, medium risk of issues", nl: "Gemiddelde eisen, deels bekende integratieflows en deels bekende technische setup, gemiddeld risico op problemen" } },
    "Low complexity": { hours: 4.0, comment: { en: "Simple requirements, known integration flows and known technical setup, small risk of issues", nl: "Eenvoudige eisen, bekende integratieflows en bekende technische setup, klein risico op problemen" } },
    "N/A": { hours: 0.0, comment: { en: "If session or task is not needed at all, don't just delete or keep as N/A", nl: "Als een sessie of taak helemaal niet nodig is, verwijder de regel niet zomaar en laat 'm niet op N/A staan" } },
  },
  setupComplexity: {
    "High complexity": { hours: 16.0, comment: { en: "High requirements, unknown integration flows, unknown technical setup, high risk of issues", nl: "Hoge eisen, onbekende integratieflows, onbekende technische setup, hoog risico op problemen" } },
    "Medium complexity": { hours: 12.0, comment: { en: "Medium requirements, partly known integration flows and partly technical setup, medium risk of issues", nl: "Gemiddelde eisen, deels bekende integratieflows en deels bekende technische setup, gemiddeld risico op problemen" } },
    "Low complexity": { hours: 8.0, comment: { en: "Simple requirements, known integration flows and known technical setup, small risk of issues", nl: "Eenvoudige eisen, bekende integratieflows en bekende technische setup, klein risico op problemen" } },
    "N/A": { hours: 0.0, comment: { en: "If session or task is not needed at all, don't just delete or keep as N/A", nl: "Als een sessie of taak helemaal niet nodig is, verwijder de regel niet zomaar en laat 'm niet op N/A staan" } },
  },
  subscriptionQty: 0,
  subscriptionUnitPrice: 2000,
};

export const ELIXIRSYNC_INTEGRATION_TEMPLATE: ElixirSyncIntegrationState = {
  enabled: false,
  hourlyRate: 150,
  streams: [
    {
      id: "es-1-project-management-organisation-besides-",
      label: "Project Management & Organisation (besides 15% Standard PM)",
      included: false,
      items: [
        {
          id: "es-1-project-management-organisation-besides--1",
          label: "Alignment Elixir Tech Team & Customer Tech Team",
          optimistic: 6.0,
          pessimistic: 10.0,
          realistic: 8.0,
        },
        {
          id: "es-1-project-management-organisation-besides--2",
          label: "Internal Alignments Elixir Team",
          optimistic: 6.0,
          pessimistic: 10.0,
          realistic: 8.0,
        },
      ],
    },
    {
      id: "es-2-testing-deployment-go-live",
      label: "Testing, Deployment & Go-Live",
      included: false,
      items: [
        {
          id: "es-2-testing-deployment-go-live-1",
          label: "Internal Test",
          optimistic: 8.0,
          pessimistic: 16.0,
          realistic: 12.0,
        },
        {
          id: "es-2-testing-deployment-go-live-2",
          label: "External UAT",
          optimistic: 8.0,
          pessimistic: 16.0,
          realistic: 12.0,
        },
        {
          id: "es-2-testing-deployment-go-live-3",
          label: "Prod Setup Deployment ",
          optimistic: 4.0,
          pessimistic: 12.0,
          realistic: 8.0,
        },
        {
          id: "es-2-testing-deployment-go-live-4",
          label: "Hypercare Support",
          optimistic: 4.0,
          pessimistic: 12.0,
          realistic: 8.0,
        },
      ],
    },
    {
      id: "es-3-standard-technical-setup",
      label: "Standard Technical Setup",
      included: false,
      items: [
        {
          id: "es-3-standard-technical-setup-1",
          label: "🔒Perform initial project code setups",
          optimistic: 1.0,
          pessimistic: 3.0,
          realistic: 2.0,
        },
        {
          id: "es-3-standard-technical-setup-2",
          label: "Setup HubSpot OAuth credentials",
          optimistic: 0.5,
          pessimistic: 1.5,
          realistic: 1.0,
        },
        {
          id: "es-3-standard-technical-setup-3",
          label: "Setup ERP credentials (username / password)",
          optimistic: 0.5,
          pessimistic: 1.5,
          realistic: 1.0,
        },
        {
          id: "es-3-standard-technical-setup-4",
          label: "🔒Setup sync scedules configuration",
          optimistic: 0.5,
          pessimistic: 1.5,
          realistic: 1.0,
        },
        {
          id: "es-3-standard-technical-setup-5",
          label: "🔒Adapt application configuration for project",
          optimistic: 1.0,
          pessimistic: 3.0,
          realistic: 2.0,
        },
        {
          id: "es-3-standard-technical-setup-6",
          label: "Create server in Microsoft Azure / Digital Ocean",
          optimistic: 3.0,
          pessimistic: 6.0,
          realistic: 4.0,
        },
        {
          id: "es-3-standard-technical-setup-7",
          label: "🔒Setup server",
          optimistic: 1.5,
          pessimistic: 5.0,
          realistic: 3.0,
        },
      ],
    },
    {
      id: "es-4-erp-companies-hubspot-companies",
      label: "ERP Companies → HubSpot Companies",
      included: false,
      items: [
        {
          id: "es-4-erp-companies-hubspot-companies-1",
          label: "Add API call to retrieve ERP accounts based on some criteria",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-2",
          label: "Add API calls to create and update ERP accounts by ID",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-3",
          label: "Create fields with custom ERP Account property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-4",
          label: "Create fields with custom HubSpot Company property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-5",
          label: "Add ‘HubSpot Relevant’ values",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-6",
          label: "ERP → HubSpot - Consumer - Add filter criteria",
          optimistic: 1.5,
          pessimistic: 3.0,
          realistic: 2.0,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-7",
          label: "ERP → HubSpot - Mappers - Add technical mappings",
          optimistic: 1.0,
          pessimistic: 4.0,
          realistic: 2.5,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-8",
          label: "ERP → HubSpot - Producer - Setup producer",
          optimistic: 1.5,
          pessimistic: 4.5,
          realistic: 3.0,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-9",
          label: "HubSpot - Event Webhook - Merge events",
          optimistic: 0.5,
          pessimistic: 1.5,
          realistic: 1.0,
        },
      ],
    },
    {
      id: "es-5-erp-contacts-hubspot-contacts",
      label: "ERP Contacts → HubSpot Contacts",
      included: false,
      items: [
        {
          id: "es-5-erp-contacts-hubspot-contacts-1",
          label: "Add API call to retrieve ERP contacts based on some criteria",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-2",
          label: "Create fields with custom ERP Contact property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-3",
          label: "Create fields with custom HubSpot Contact property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-4",
          label: "Add ‘HubSpot Relevant’ values",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-5",
          label: "ERP → HubSpot - Consumer - Add filter criteria",
          optimistic: 1.5,
          pessimistic: 3.0,
          realistic: 2.0,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-6",
          label: "ERP → HubSpot - Mappers - Add technical mappings",
          optimistic: 1.0,
          pessimistic: 4.0,
          realistic: 2.5,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-7",
          label: "ERP → HubSpot - Producer - Setup producer",
          optimistic: 1.5,
          pessimistic: 4.5,
          realistic: 3.0,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-8",
          label: "HubSpot - Event Webhook - Company association based on External Account ID",
          optimistic: 1.0,
          pessimistic: 2.0,
          realistic: 1.5,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-9",
          label: "HubSpot - Event Webhook - Merge events",
          optimistic: 0.5,
          pessimistic: 1.5,
          realistic: 1.0,
        },
      ],
    },
    {
      id: "es-6-hubspot-contacts-erp-contacts",
      label: "HubSpot Contacts → ERP Contacts",
      included: false,
      items: [
        {
          id: "es-6-hubspot-contacts-erp-contacts-1",
          label: "Add API calls to create and update ERP contacts by ID",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-6-hubspot-contacts-erp-contacts-2",
          label: "HubSpot → ERP - Consumer - Configure List consumer",
          optimistic: 1.5,
          pessimistic: 3.0,
          realistic: 2.0,
        },
        {
          id: "es-6-hubspot-contacts-erp-contacts-3",
          label: "HubSpot → ERP - Mappers - Add technical mappings",
          optimistic: 1.0,
          pessimistic: 4.0,
          realistic: 2.5,
        },
        {
          id: "es-6-hubspot-contacts-erp-contacts-4",
          label: "HubSpot → ERP - Producer - Setup producer",
          optimistic: 2.0,
          pessimistic: 5.0,
          realistic: 3.5,
        },
      ],
    },
    {
      id: "es-7-erp-active-leads-hubspot-contacts",
      label: "ERP Active Leads → HubSpot Contacts",
      included: true,
      items: [
        {
          id: "es-7-erp-active-leads-hubspot-contacts-1",
          label: "Add API call to retrieve ERP leads based on some criteria",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-2",
          label: "Create fields with custom ERP Lead property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-3",
          label: "Create fields with custom HubSpot Lead property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-4",
          label: "Add ‘HubSpot Relevant’ values",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-5",
          label: "Active Leads - ERP → HubSpot - Consumer - Add filter criteria",
          optimistic: 1.5,
          pessimistic: 2.5,
          realistic: 2.0,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-6",
          label: "Active Leads - ERP → HubSpot - Webhook - Create webhook",
          optimistic: 1.0,
          pessimistic: 3.0,
          realistic: 1.5,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-7",
          label: "Active Leads - ERP → HubSpot - Mappers - Add technical mappings",
          optimistic: 1.0,
          pessimistic: 4.0,
          realistic: 2.5,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-8",
          label: "Active Leads - ERP → HubSpot - Producer - Setup producer",
          optimistic: 1.5,
          pessimistic: 4.5,
          realistic: 3.0,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-9",
          label: "Active Leads - HubSpot - Event Webhook - Company association based on External Account ID",
          optimistic: 1.0,
          pessimistic: 2.0,
          realistic: 1.5,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-10",
          label: "Active Leads - HubSpot - Event Webhook - Contact association based on External Contact ID",
          optimistic: 1.0,
          pessimistic: 2.0,
          realistic: 1.5,
        },
      ],
    },
    {
      id: "es-8-hubspot-contacts-erp-active-leads",
      label: "HubSpot Contacts → ERP Active Leads",
      included: true,
      items: [
        {
          id: "es-8-hubspot-contacts-erp-active-leads-1",
          label: "Add API calls to create and update ERP leads by ID",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-8-hubspot-contacts-erp-active-leads-2",
          label: "Active Leads - HubSpot → ERP - Consumer - Configure List consumer",
          optimistic: 2.0,
          pessimistic: 4.0,
          realistic: 3.0,
        },
        {
          id: "es-8-hubspot-contacts-erp-active-leads-3",
          label: "Active Leads - HubSpot → ERP - Workflow Webhook - Create webhook",
          optimistic: 1.5,
          pessimistic: 3.0,
          realistic: 2.5,
        },
        {
          id: "es-8-hubspot-contacts-erp-active-leads-4",
          label: "Active Leads - HubSpot → ERP - Mappers - Add technical mappings",
          optimistic: 1.0,
          pessimistic: 4.0,
          realistic: 2.5,
        },
        {
          id: "es-8-hubspot-contacts-erp-active-leads-5",
          label: "Active Leads - HubSpot → ERP - Producer - Setup producer",
          optimistic: 2.0,
          pessimistic: 5.0,
          realistic: 3.5,
        },
      ],
    },
    {
      id: "es-9-erp-inactive-leads-hubspot-contacts",
      label: "ERP Inactive Leads → HubSpot Contacts",
      included: true,
      items: [
        {
          id: "es-9-erp-inactive-leads-hubspot-contacts-1",
          label: "Inactive Leads - ERP → HubSpot - Consumer - Add filter criteria",
          optimistic: 1.5,
          pessimistic: 2.5,
          realistic: 2.0,
        },
        {
          id: "es-9-erp-inactive-leads-hubspot-contacts-2",
          label: "Inactive Leads - ERP → HubSpot - Deactivate in SyncDB",
          optimistic: 1.0,
          pessimistic: 1.5,
          realistic: 1.25,
        },
        {
          id: "es-9-erp-inactive-leads-hubspot-contacts-3",
          label: "Inactive Leads - ERP → HubSpot - Update in ERP",
          optimistic: 2.0,
          pessimistic: 3.0,
          realistic: 2.5,
        },
        {
          id: "es-9-erp-inactive-leads-hubspot-contacts-4",
          label: "Inactive Leads - ERP → HubSpot - Update HubSpot external entity",
          optimistic: 2.0,
          pessimistic: 3.0,
          realistic: 2.5,
        },
      ],
    },
    {
      id: "es-10-erp-opportunities-hubspot-deals",
      label: "ERP Opportunities → HubSpot Deals",
      included: false,
      items: [
        {
          id: "es-10-erp-opportunities-hubspot-deals-1",
          label: "Add API call to retrieve ERP opportunities based on some criteria",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-2",
          label: "Create fields with custom ERP Opportunity property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-3",
          label: "Create fields with custom HubSpot Deal property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-4",
          label: "Add ‘HubSpot relevant’ values",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-5",
          label: "Configure environmental IDs (deal stages, pipeline IDs,..)",
          optimistic: 0.5,
          pessimistic: 1.0,
          realistic: 0.75,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-6",
          label: "ERP → HubSpot - Consumer - Add filter criteria",
          optimistic: 1.5,
          pessimistic: 2.5,
          realistic: 2.0,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-7",
          label: "ERP → HubSpot - Mappers - Add technical mappings",
          optimistic: 1.0,
          pessimistic: 4.0,
          realistic: 2.5,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-8",
          label: "ERP → HubSpot - Producer - Setup producer",
          optimistic: 2.0,
          pessimistic: 5.0,
          realistic: 3.5,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-9",
          label: "HubSpot - Event Webhook - Company association based on External Account ID",
          optimistic: 1.0,
          pessimistic: 2.0,
          realistic: 1.5,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-10",
          label: "HubSpot - Event Webhook - Contact association based on External Contact ID",
          optimistic: 1.0,
          pessimistic: 2.0,
          realistic: 1.5,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-11",
          label: "HubSpot - Event Webhook - Merge events",
          optimistic: 0.5,
          pessimistic: 1.5,
          realistic: 1.0,
        },
      ],
    },
    {
      id: "es-11-erp-line-items-hubspot-line-items",
      label: "ERP Line Items → HubSpot Line Items",
      included: false,
      items: [
        {
          id: "es-11-erp-line-items-hubspot-line-items-1",
          label: "Add API call to retrieve ERP line items based on Opportunity ID (unless included with Opportunities)",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-11-erp-line-items-hubspot-line-items-2",
          label: "Create fields with custom ERP Line Item property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-11-erp-line-items-hubspot-line-items-3",
          label: "Create fields with custom HubSpot Line Item property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-11-erp-line-items-hubspot-line-items-4",
          label: "ERP → HubSpot - Consumer - Consume based on previously synced opportunity IDs (unless Line Items included with Opportunities sync)",
          optimistic: 3.0,
          pessimistic: 9.0,
          realistic: 6.0,
        },
        {
          id: "es-11-erp-line-items-hubspot-line-items-5",
          label: "ERP → HubSpot - Mappers - Add technical mappings",
          optimistic: 1.5,
          pessimistic: 5.0,
          realistic: 3.5,
        },
        {
          id: "es-11-erp-line-items-hubspot-line-items-6",
          label: "ERP → HubSpot - Producer - Setup producer",
          optimistic: 2.0,
          pessimistic: 5.0,
          realistic: 3.5,
        },
        {
          id: "es-11-erp-line-items-hubspot-line-items-7",
          label: "HubSpot - Event Webhook - Deal association based on External Opportunity ID",
          optimistic: 1.0,
          pessimistic: 2.0,
          realistic: 1.5,
        },
      ],
    },
    {
      id: "es-12-erp-custom-object-hubspot-custom-object",
      label: "ERP Custom Object → HubSpot Custom Object",
      included: false,
      items: [
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-1",
          label: "Add API call to retrieve CRM/ERP Object based on some criteria",
          optimistic: 0.5,
          pessimistic: 1.0,
          realistic: 0.75,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-2",
          label: "Add API calls to create and update CRM/ERP Object",
          optimistic: 0.5,
          pessimistic: 1.0,
          realistic: 0.75,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-3",
          label: "Create fields wit custom CRM/ERP Object property names",
          optimistic: 1.0,
          pessimistic: 2.5,
          realistic: 1.5,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-4",
          label: "Create fields wit custom Hubspot Object property names",
          optimistic: 1.0,
          pessimistic: 2.5,
          realistic: 1.5,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-5",
          label: "Configure Hubspot Custom Object ID for eac environment",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-6",
          label: "Add ‘Hubspot Relevant’ values",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-7",
          label: "CRM/ERP → Hubspot - Consumer - Add filter criteria",
          optimistic: 3.0,
          pessimistic: 9.0,
          realistic: 6.0,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-8",
          label: "CRM/ERP → Hubspot - Mappers - Add tecnical mappings",
          optimistic: 2.5,
          pessimistic: 6.0,
          realistic: 4.5,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-9",
          label: "CRM/ERP → Hubspot - Producer - Setup producer",
          optimistic: 2.0,
          pessimistic: 5.0,
          realistic: 3.5,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-10",
          label: "Hubspot - Workflow Webook - Associations (per association)",
          optimistic: 6.0,
          pessimistic: 10.0,
          realistic: 8.0,
        },
      ],
    },
  ],
  subscriptionQty: 0,
  subscriptionUnitPrice: 5000,
};

export const DEFAULT_PM_RATE = 150;
export const DEFAULT_PM_PERCENT = 0.15;

export function createDefaultEstimationState(): EstimationState {
  return {
    locale: "en",
    standardWorkstreams: structuredClone(STANDARD_WORKSTREAM_TEMPLATES),
    thirdPartyIntegration: structuredClone(THIRD_PARTY_INTEGRATION_TEMPLATE),
    elixirSyncIntegration: structuredClone(ELIXIRSYNC_INTEGRATION_TEMPLATE),
    pmRate: DEFAULT_PM_RATE,
    pmPercent: DEFAULT_PM_PERCENT,
    hubspotLicense: createDefaultHubSpotLicenseState(),
  };
}

/**
 * Standard rate-card prices, keyed by workstream key (plus the two
 * integrations and "pm"). These stay fixed even when a specific
 * estimation's hourlyRate is overridden, so the UI can show "this
 * estimation deviates from the standard rate" next to the editable field.
 */
export const DEFAULT_HOURLY_RATES: Record<string, number> = {
  ...Object.fromEntries(STANDARD_WORKSTREAM_TEMPLATES.map((ws) => [ws.key, ws.hourlyRate])),
  third_party_integration: THIRD_PARTY_INTEGRATION_TEMPLATE.hourlyRate,
  elixirsync_integration: ELIXIRSYNC_INTEGRATION_TEMPLATE.hourlyRate,
  pm: DEFAULT_PM_RATE,
};
