// AUTO-GENERATED from the Elixir Project Estimation Template V2 (.xlsx).
// Regenerate via scripts in the session that extracted this if the source workbook changes.
// NOTE: fixes a real bug in the source spreadsheet where several tabs' "Setup" rows
// looked up the PREVIOUS row's complexity dropdown instead of their own (off-by-one
// copy-paste error in Sales/CMS/DealHub/HS Deployment & Go-Live tabs). Here every line
// item always uses its own complexity selection, as originally intended.

import type {
  StandardWorkstream,
  ThirdPartyIntegrationState,
  ElixirSyncIntegrationState,
  EstimationState,
} from './types';

export const STANDARD_WORKSTREAM_TEMPLATES: StandardWorkstream[] = [
  {
    key: "business_assessment",
    label: "Business Assessment",
    enabled: true,
    hourlyRate: 175,
    items: [
      {
        id: "business_assessment-1-strategy-interview",
        activity: "Session",
        topic: "Strategy Interview",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "business_assessment-2-marketing-interview",
        activity: "Session",
        topic: "Marketing Interview",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "business_assessment-3-sales-interview",
        activity: "Session",
        topic: "Sales Interview",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "business_assessment-4-service-interview",
        activity: "Session",
        topic: "Service Interview",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "business_assessment-5-datait-interview-reverse-demo",
        activity: "Session",
        topic: "Data/IT Interview - Reverse demo",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "business_assessment-6-solution-design-workshop",
        activity: "Session",
        topic: "Solution design workshop",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: "Only for uni-dimensional projects",
        enabled: true,
      },
      {
        id: "business_assessment-7-assessment-presentation",
        activity: "Session",
        topic: "Assessment presentation",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: "Only for multi dimensional projects",
        enabled: true,
      },
      {
        id: "business_assessment-8-create-solution-design-user-stories",
        activity: "Desk work",
        topic: "Create solution design & user stories",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: "Only for uni-dimensional projects",
        enabled: true,
      },
      {
        id: "business_assessment-9-prepare-assessment-presentation",
        activity: "Desk work",
        topic: "Prepare assessment presentation",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: "Only for multi dimensional projects",
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -1.0, comment: "1,5 hr Session with 2 people, no preparation time" },
    "Standard": { hours: 0.0, comment: "1,5 hr Session with 2 people, normal preparation time" },
    "Medium": { hours: 1.0, comment: "2 hr Session with 2 people, medium complexity and medium preparation time" },
    "High": { hours: 2.0, comment: "2 hr Session with 2 people, high complexity and high preparation time" },
  },
    setupComplexity: {
    "Low": { hours: -1.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 1.0, comment: null },
    "High": { hours: 2.0, comment: null },
  },
  },
  {
    key: "technical_assessment",
    label: "Technical Assessment",
    enabled: true,
    hourlyRate: 175,
    items: [
      {
        id: "technical_assessment-1-understanding-situation-processes",
        activity: "Session",
        topic: "Understanding situation & processes",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "technical_assessment-2-best-practice-integration-flow",
        activity: "Session",
        topic: "Best-practice integration flow",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "technical_assessment-3-adapted-integration-flow",
        activity: "Session",
        topic: "Adapted integration flow",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "technical_assessment-4-data-mapping-i",
        activity: "Session",
        topic: "Data mapping I",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "technical_assessment-5-functional-requirements",
        activity: "Session",
        topic: "Functional Requirements",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "technical_assessment-6-integration-flow-definition",
        activity: "Setup",
        topic: "Integration Flow Definition",
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "technical_assessment-7-mapping-file",
        activity: "Setup",
        topic: "Mapping File",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "technical_assessment-8-functional-requirements-document",
        activity: "Setup",
        topic: "Functional Requirements Document",
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: "1,5 hr Session with 2 people, no preparation time" },
    "Standard": { hours: 0.0, comment: "1,5 hr Session with 2 people, normal preparation time" },
    "Medium": { hours: 2.0, comment: "2 hr Session with 2 people, medium complexity and medium preparation time" },
    "High": { hours: 4.0, comment: "2 hr Session with 2 people, high complexity and high preparation time" },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
  {
    key: "data_migration",
    label: "Data Migration",
    enabled: true,
    hourlyRate: 150,
    items: [
      {
        id: "data_migration-1-kick-off-hs-best-practices-customer-inpu",
        activity: "Session",
        topic: "Kick-off - HS Best Practices & Customer Input",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-2-data-mapping-i",
        activity: "Session",
        topic: "Data Mapping I",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-3-data-mapping-ii",
        activity: "Session",
        topic: "Data Mapping II",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-4-alignment-before-loading-in-test",
        activity: "Session",
        topic: "Alignment before loading in Test",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-5-data-validation-in-test",
        activity: "Session",
        topic: "Data Validation in Test",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-6-alignment-before-loading-in-production",
        activity: "Session",
        topic: "Alignment before loading in Production",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-7-data-validation-in-prod",
        activity: "Session",
        topic: "Data Validation in Prod",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-8-data-transformation",
        activity: "Setup",
        topic: "Data Transformation",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-9-data-loading-in-test",
        activity: "Setup",
        topic: "Data Loading in Test",
        standardEffort: 6.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "data_migration-10-data-loading-in-prod",
        activity: "Setup",
        topic: "Data Loading in Prod",
        standardEffort: 6.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: "1,5 hr Session with 2 people, no preparation time" },
    "Standard": { hours: 0.0, comment: "1,5 hr Session with 2 people, normal preparation time" },
    "Medium": { hours: 2.0, comment: "1,5 hr Session with 2 people, medium complexity and medium preparation time" },
    "High": { hours: 4.0, comment: "1,5 hr Session with 2 people, high complexity and high preparation time" },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
  {
    key: "sales_implementation",
    label: "Sales Implementation",
    enabled: true,
    hourlyRate: 150,
    items: [
      {
        id: "sales_implementation-1-sales-kick-off-workshop",
        activity: "Session",
        topic: "Sales Kick-off Workshop",
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-2-company-contact-lead-activity-mgmt",
        activity: "Session",
        topic: "Company & Contact, lead & activity Mgmt",
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-3-deal-pipeline-management",
        activity: "Session",
        topic: "Deal & Pipeline management",
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-4-quote-management",
        activity: "Session",
        topic: "Quote management",
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-5-sales-reporting-authorizations",
        activity: "Session",
        topic: "Sales Reporting & Authorizations",
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-6-setup-checkin-session-i",
        activity: "Session",
        topic: "Setup Checkin Session I",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-7-setup-checkin-session-ii",
        activity: "Session",
        topic: "Setup Checkin Session II",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-8-final-checkin-session-before-go-live",
        activity: "Session",
        topic: "Final Checkin Session (before Go-Live)",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-9-sales-marketing-alignment",
        activity: "Session",
        topic: "Sales & marketing alignment",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-10-companies",
        activity: "Setup",
        topic: "Companies",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-11-contacts",
        activity: "Setup",
        topic: "Contacts",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-12-lead-management",
        activity: "Setup",
        topic: "Lead management",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-13-deals",
        activity: "Setup",
        topic: "Deals",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-14-quoting",
        activity: "Setup",
        topic: "Quoting",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-15-dashboards-reports",
        activity: "Setup",
        topic: "Dashboards & reports",
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "sales_implementation-16-users-teams-permission-sets",
        activity: "Setup",
        topic: "Users, Teams & Permission sets",
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: "1,5 hr Session with 2 people, no preparation time" },
    "Standard": { hours: 0.0, comment: "3 hr Session with 2 people, normal preparation time" },
    "Medium": { hours: 2.0, comment: "3 hr Session with 2 people, medium complexity and medium preparation time" },
    "High": { hours: 4.0, comment: "3 hr Session with 2 people, high complexity and high preparation time" },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
  {
    key: "service_implementation",
    label: "Service Implementation",
    enabled: true,
    hourlyRate: 150,
    items: [
      {
        id: "service_implementation-1-service-kick-off-workshop",
        activity: "Session",
        topic: "Service kick-off Workshop",
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-2-company-contact-management",
        activity: "Session",
        topic: "Company & contact management",
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-3-ticket-management",
        activity: "Session",
        topic: "Ticket management",
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-4-knowledge-base-feedback-surveys",
        activity: "Session",
        topic: "Knowledge base & feedback surveys",
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-5-service-reporting-authorizations",
        activity: "Session",
        topic: "Service reporting & Authorizations",
        standardEffort: 8.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-6-setup-checkin-session-i",
        activity: "Session",
        topic: "Setup Checkin Session I",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-7-setup-checkin-session-ii",
        activity: "Session",
        topic: "Setup Checkin Session II",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-8-final-wrap-up-before-training",
        activity: "Session",
        topic: "Final wrap-up (before training)",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-9-companies",
        activity: "Setup",
        topic: "Companies",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-10-contacts",
        activity: "Setup",
        topic: "Contacts",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-11-tickets",
        activity: "Setup",
        topic: "Tickets",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-12-customer-portal",
        activity: "Setup",
        topic: "Customer portal",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-13-knowledge-base",
        activity: "Setup",
        topic: "Knowledge base",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-14-surveys",
        activity: "Setup",
        topic: "Surveys",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-15-dashboards-reports",
        activity: "Setup",
        topic: "Dashboards & reports",
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "service_implementation-16-users-teams-permission-sets",
        activity: "Setup",
        topic: "Users, Teams & Permission sets",
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: "1,5 hr Session with 2 people, no preparation time" },
    "Standard": { hours: 0.0, comment: "3 hr Session with 2 people, normal preparation time" },
    "Medium": { hours: 2.0, comment: "3 hr Session with 2 people, medium complexity and medium preparation time" },
    "High": { hours: 4.0, comment: "3 hr Session with 2 people, high complexity and high preparation time" },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
  {
    key: "marketing_implementation",
    label: "Marketing Implementation",
    enabled: true,
    hourlyRate: 150,
    items: [
      {
        id: "marketing_implementation-1-marketing-kick-off-tech-questionnaire",
        activity: "Session",
        topic: "Marketing Kick-off (Tech Questionnaire)",
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-2-gdpr-marketing-contacts",
        activity: "Session",
        topic: "GDPR & marketing contacts",
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-3-campaign-definition-technical-set-up",
        activity: "Session",
        topic: "Campaign Definition, Technical set-up",
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-4-buyer-personas-buyers-journey",
        activity: "Session",
        topic: "Buyer Personas & Buyers Journey",
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-5-lead-qualification-scoring-campaign-flow",
        activity: "Session",
        topic: "Lead qualification / scoring & Campaign Flow",
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-6-assets-training-i",
        activity: "Session",
        topic: "Assets Training I",
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-7-assets-training-ii",
        activity: "Session",
        topic: "Assets Training II",
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-8-campaign-go-live",
        activity: "Session",
        topic: "Campaign go-live",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-9-marketing-reporting-analytics",
        activity: "Session",
        topic: "Marketing reporting & analytics",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-10-setup-checkin-session-i",
        activity: "Session",
        topic: "Setup Checkin Session I",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-11-setup-checkin-session-ii",
        activity: "Session",
        topic: "Setup Checkin Session II",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-12-campaign-follow-up",
        activity: "Session",
        topic: "Campaign Follow-up ",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-13-general-set-up-tracking-link-domains-sub",
        activity: "Setup",
        topic: "General set-up: Tracking link, Domains, Subdomains, Compliance, Plug&Play Integrations",
        standardEffort: 6.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-14-gdpr-set-up-consent-subscription-types-c",
        activity: "Setup",
        topic: "GDPR set-up: Consent, subscription types, cookie banner, DOI, marketing contacts",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-15-lead-qualification-scoring",
        activity: "Setup",
        topic: "Lead Qualification / Scoring",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-16-campaign-assets-ads-social-landing-pages",
        activity: "Setup",
        topic: "Campaign assets: Ads, Social, Landing pages, Forms, Mails, Workflows",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-17-dashboards-reports",
        activity: "Setup",
        topic: "Dashboards & reports",
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "marketing_implementation-18-users-teams-permission-sets",
        activity: "Setup",
        topic: "Users, Teams & Permission sets",
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: "1,5 hr Session with 2 people, no preparation time" },
    "Standard": { hours: 0.0, comment: "1,5 hr Session with 2 people, normal preparation time" },
    "Medium": { hours: 2.0, comment: "1,5 hr Session with 2 people, medium complexity and medium preparation time" },
    "High": { hours: 4.0, comment: "1,5 hr Session with 2 people, high complexity and high preparation time" },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
  {
    key: "cms_implementation",
    label: "CMS Implementation",
    enabled: true,
    hourlyRate: 150,
    items: [
      {
        id: "cms_implementation-1-cms-kick-off-approach",
        activity: "Session",
        topic: "CMS Kick-off / Approach",
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-2-setup-future-branding",
        activity: "Session",
        topic: "Setup & future Branding",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-3-page-template-review",
        activity: "Session",
        topic: "Page Template Review",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-4-cms-training-i",
        activity: "Session",
        topic: "CMS Training I",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-5-cms-training-ii",
        activity: "Session",
        topic: "CMS Training II",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-6-migration-session-i",
        activity: "Session",
        topic: "Migration Session I",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-7-migration-session-ii",
        activity: "Session",
        topic: "Migration Session II",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-8-setup-checkin-fine-tuning-alignment-i",
        activity: "Session",
        topic: "Setup Checkin & Fine Tuning Alignment I",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-9-setup-checkin-fine-tuning-alignment-ii",
        activity: "Session",
        topic: "Setup Checkin & Fine Tuning Alignment II",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-10-setup-branding",
        activity: "Setup",
        topic: "Setup & Branding",
        standardEffort: 8.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-11-page-templates-modules",
        activity: "Setup",
        topic: "Page Templates & Modules",
        standardEffort: 12.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-12-fine-tuning-after-feedback",
        activity: "Setup",
        topic: "Fine Tuning after Feedback",
        standardEffort: 8.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-13-redirect-setup",
        activity: "Setup",
        topic: "Redirect Setup",
        standardEffort: 8.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-14-migration-support",
        activity: "Setup",
        topic: "Migration Support",
        standardEffort: 16.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "cms_implementation-15-users-teams-permission-sets",
        activity: "Setup",
        topic: "Users, Teams & Permission sets",
        standardEffort: 2.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: "1,5 hr Session with 2 people, no preparation time" },
    "Standard": { hours: 0.0, comment: "1,5 hr Session with 2 people, normal preparation time" },
    "Medium": { hours: 2.0, comment: "1,5 hr Session with 2 people, medium complexity and medium preparation time" },
    "High": { hours: 4.0, comment: "1,5 hr Session with 2 people, high complexity and high preparation time" },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
  {
    key: "dealhub_implementation",
    label: "DealHub Implementation",
    enabled: true,
    hourlyRate: 150,
    items: [
      {
        id: "dealhub_implementation-1-cpq-kick-off-approach",
        activity: "Session",
        topic: "CPQ Kick-off / Approach",
        standardEffort: 6.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-2-setup-analysis-reverse-demo",
        activity: "Session",
        topic: "Setup Analysis, Reverse Demo",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-3-playbook-setup",
        activity: "Session",
        topic: "Playbook Setup",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-4-product-setup",
        activity: "Session",
        topic: "Product Setup",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-5-pricing-discount-setup",
        activity: "Session",
        topic: "Pricing & Discount Setup",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-6-pricing-discount-rule-setup",
        activity: "Session",
        topic: "Pricing & Discount Rule Setup",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-7-data-migration-alignment",
        activity: "Session",
        topic: "Data Migration Alignment",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-8-dealroom-setup",
        activity: "Session",
        topic: "DealRoom Setup",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-9-setup-checkin-session-i",
        activity: "Session",
        topic: "Setup Checkin Session I",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-10-setup-checkin-session-ii",
        activity: "Session",
        topic: "Setup Checkin Session II",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-11-final-wrap-up-before-training",
        activity: "Session",
        topic: "Final wrap-up (before training)",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-12-playbook-setup",
        activity: "Setup",
        topic: "Playbook Setup",
        standardEffort: 8.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-13-product-setup",
        activity: "Setup",
        topic: "Product Setup",
        standardEffort: 12.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-14-pricing-discount-setup",
        activity: "Setup",
        topic: "Pricing & Discount Setup",
        standardEffort: 8.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-15-pricing-discount-rule-setup",
        activity: "Setup",
        topic: "Pricing & Discount Rule Setup",
        standardEffort: 8.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-16-data-migration-alignment",
        activity: "Setup",
        topic: "Data Migration Alignment",
        standardEffort: 16.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-17-dealroom",
        activity: "Setup",
        topic: "DealRoom",
        standardEffort: 8.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "dealhub_implementation-18-fine-tuning-rework",
        activity: "Setup",
        topic: "Fine Tuning, Rework",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: "1,5 hr Session with 2 people, no preparation time" },
    "Standard": { hours: 0.0, comment: "3 hr Session with 2 people, normal preparation time" },
    "Medium": { hours: 2.0, comment: "3 hr Session with 2 people, medium complexity and medium preparation time" },
    "High": { hours: 4.0, comment: "3 hr Session with 2 people, high complexity and high preparation time" },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
  {
    key: "deployment_golive",
    label: "HubSpot Deployment & Go-Live",
    enabled: true,
    hourlyRate: 150,
    items: [
      {
        id: "deployment_golive-1-sales-key-user-training",
        activity: "Session",
        topic: "Sales key user training",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-2-service-key-user-training",
        activity: "Session",
        topic: "Service key user training",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-3-marketing-key-user-training",
        activity: "Session",
        topic: "Marketing key user training",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-4-super-admin-training",
        activity: "Session",
        topic: "Super Admin training",
        standardEffort: 3.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-5-sales-end-user-training-6-8-users-sessio",
        activity: "Session",
        topic: "Sales end user training (6-8 users / session)",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-6-service-end-user-training-6-8-users-sess",
        activity: "Session",
        topic: "Service end user training (6-8 users / session)",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-7-marketing-end-user-training-6-8-users-se",
        activity: "Session",
        topic: "Marketing end user training (6-8 users / session)",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-8-hypercare-support",
        activity: "Session",
        topic: "Hypercare Support",
        standardEffort: 4.0,
        complexityTable: "session",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-9-deployment-sales-prod",
        activity: "Setup",
        topic: "Deployment Sales Prod",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-10-deployment-service-prod",
        activity: "Setup",
        topic: "Deployment Service Prod",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-11-deployment-marketing-prod",
        activity: "Setup",
        topic: "Deployment Marketing Prod",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
      {
        id: "deployment_golive-12-setup-hypercare",
        activity: "Setup",
        topic: "Setup Hypercare",
        standardEffort: 4.0,
        complexityTable: "setup",
        complexity: "Standard",
        comment: null,
        enabled: true,
      },
    ],
    sessionComplexity: {
    "Low": { hours: -2.0, comment: "1 Session, one consultant, no preperation time" },
    "Standard": { hours: 0.0, comment: "1 Session, one consultant, normal preperation time" },
    "Medium": { hours: 2.0, comment: "1 Session, one consultant, medium preperation time" },
    "High": { hours: 4.0, comment: "1 Session, one consultant, high preperation time" },
  },
    setupComplexity: {
    "Low": { hours: -2.0, comment: null },
    "Standard": { hours: 0.0, comment: null },
    "Medium": { hours: 2.0, comment: null },
    "High": { hours: 4.0, comment: null },
  },
  },
];

export const THIRD_PARTY_INTEGRATION_TEMPLATE: ThirdPartyIntegrationState = {
  enabled: false,
  hourlyRate: 150,
  items: [
    {
      id: "tp-1-lead",
      activity: "Setup",
      topic: "Lead",
      from: "Hubspot",
      to: "ERP",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-2-lead",
      activity: "Setup",
      topic: "Lead",
      from: "ERP",
      to: "Hubspot",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-3-contact",
      activity: "Setup",
      topic: "Contact",
      from: "Hubspot",
      to: "ERP",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-4-contact",
      activity: "Setup",
      topic: "Contact",
      from: "ERP",
      to: "Hubspot",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-5-company",
      activity: "Setup",
      topic: "Company",
      from: "Hubspot",
      to: "ERP",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-6-company",
      activity: "Setup",
      topic: "Company",
      from: "ERP",
      to: "Hubspot",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-7-deal",
      activity: "Setup",
      topic: "Deal",
      from: "ERP",
      to: "Hubspot",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-8-deal-line-item",
      activity: "Setup",
      topic: "Deal Line Item",
      from: "ERP",
      to: "Hubspot",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-9-order",
      activity: "Setup",
      topic: "Order ",
      from: "ERP",
      to: "Hubspot",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-10-order-line-item",
      activity: "Setup",
      topic: "Order Line Item",
      from: "ERP",
      to: "Hubspot",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-11-custom-object",
      activity: "Setup",
      topic: "Custom Object",
      from: "Hubspot",
      to: "ERP",
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-12-prod-deployment",
      activity: "Setup",
      topic: "Prod Deployment",
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-13-hypercare",
      activity: "Setup",
      topic: "Hypercare",
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-14-kick-off-session",
      activity: "Session",
      topic: "Kick-Off Session",
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-15-setup-checkin-session-i",
      activity: "Session",
      topic: "Setup Checkin Session I",
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-16-setup-checkin-session-ii",
      activity: "Session",
      topic: "Setup Checkin Session II",
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-17-setup-checkin-session-iii",
      activity: "Session",
      topic: "Setup Checkin Session III",
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-18-pm-checkins",
      activity: "Session",
      topic: "PM Checkins",
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-19-external-testing-uat",
      activity: "Session",
      topic: "External Testing (UAT)",
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
    {
      id: "tp-20-internal-testing-uat",
      activity: "Session",
      topic: "Internal Testing (UAT)",
      from: null,
      to: null,
      complexity: "N/A",
      enabled: true,
    },
  ],
  sessionComplexity: {
    "High complexity": { hours: 12.0, comment: "High requirements, unknown integration flows, unknown technical setup, high risk of issues" },
    "Medium complexity": { hours: 8.0, comment: "Medium requirements, partly known integration flows and partly technical setup, medium risk of issues" },
    "Low complexity": { hours: 4.0, comment: "Simple requirements, known integration flows and known technical setup, small risk of issues" },
    "N/A": { hours: 0.0, comment: "If session or task is not needed at all, don't just delete or keep as N/A" },
  },
  setupComplexity: {
    "High complexity": { hours: 16.0, comment: "High requirements, unknown integration flows, unknown technical setup, high risk of issues" },
    "Medium complexity": { hours: 12.0, comment: "Medium requirements, partly known integration flows and partly technical setup, medium risk of issues" },
    "Low complexity": { hours: 8.0, comment: "Simple requirements, known integration flows and known technical setup, small risk of issues" },
    "N/A": { hours: 0.0, comment: "If session or task is not needed at all, don't just delete or keep as N/A" },
  },
  subscriptionQty: 0,
  subscriptionUnitPrice: 2000,
};

export const ELIXIRSYNC_INTEGRATION_TEMPLATE: ElixirSyncIntegrationState = {
  enabled: false,
  hourlyRate: 150,
  streams: [
    {
      id: "es-1-project-management-organisation-besides-",
      label: "Project Management & Organisation (besides 15% Standard PM)",
      included: false,
      items: [
        {
          id: "es-1-project-management-organisation-besides--1",
          label: "Alignment Elixir Tech Team & Customer Tech Team",
          optimistic: 6.0,
          pessimistic: 10.0,
          realistic: 8.0,
        },
        {
          id: "es-1-project-management-organisation-besides--2",
          label: "Internal Alignments Elixir Team",
          optimistic: 6.0,
          pessimistic: 10.0,
          realistic: 8.0,
        },
      ],
    },
    {
      id: "es-2-testing-deployment-go-live",
      label: "Testing, Deployment & Go-Live",
      included: false,
      items: [
        {
          id: "es-2-testing-deployment-go-live-1",
          label: "Internal Test",
          optimistic: 8.0,
          pessimistic: 16.0,
          realistic: 12.0,
        },
        {
          id: "es-2-testing-deployment-go-live-2",
          label: "External UAT",
          optimistic: 8.0,
          pessimistic: 16.0,
          realistic: 12.0,
        },
        {
          id: "es-2-testing-deployment-go-live-3",
          label: "Prod Setup Deployment ",
          optimistic: 4.0,
          pessimistic: 12.0,
          realistic: 8.0,
        },
        {
          id: "es-2-testing-deployment-go-live-4",
          label: "Hypercare Support",
          optimistic: 4.0,
          pessimistic: 12.0,
          realistic: 8.0,
        },
      ],
    },
    {
      id: "es-3-standard-technical-setup",
      label: "Standard Technical Setup",
      included: false,
      items: [
        {
          id: "es-3-standard-technical-setup-1",
          label: "🔒Perform initial project code setups",
          optimistic: 1.0,
          pessimistic: 3.0,
          realistic: 2.0,
        },
        {
          id: "es-3-standard-technical-setup-2",
          label: "Setup HubSpot OAuth credentials",
          optimistic: 0.5,
          pessimistic: 1.5,
          realistic: 1.0,
        },
        {
          id: "es-3-standard-technical-setup-3",
          label: "Setup ERP credentials (username / password)",
          optimistic: 0.5,
          pessimistic: 1.5,
          realistic: 1.0,
        },
        {
          id: "es-3-standard-technical-setup-4",
          label: "🔒Setup sync scedules configuration",
          optimistic: 0.5,
          pessimistic: 1.5,
          realistic: 1.0,
        },
        {
          id: "es-3-standard-technical-setup-5",
          label: "🔒Adapt application configuration for project",
          optimistic: 1.0,
          pessimistic: 3.0,
          realistic: 2.0,
        },
        {
          id: "es-3-standard-technical-setup-6",
          label: "Create server in Microsoft Azure / Digital Ocean",
          optimistic: 3.0,
          pessimistic: 6.0,
          realistic: 4.0,
        },
        {
          id: "es-3-standard-technical-setup-7",
          label: "🔒Setup server",
          optimistic: 1.5,
          pessimistic: 5.0,
          realistic: 3.0,
        },
      ],
    },
    {
      id: "es-4-erp-companies-hubspot-companies",
      label: "ERP Companies → HubSpot Companies",
      included: false,
      items: [
        {
          id: "es-4-erp-companies-hubspot-companies-1",
          label: "Add API call to retrieve ERP accounts based on some criteria",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-2",
          label: "Add API calls to create and update ERP accounts by ID",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-3",
          label: "Create fields with custom ERP Account property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-4",
          label: "Create fields with custom HubSpot Company property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-5",
          label: "Add ‘HubSpot Relevant’ values",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-6",
          label: "ERP → HubSpot - Consumer - Add filter criteria",
          optimistic: 1.5,
          pessimistic: 3.0,
          realistic: 2.0,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-7",
          label: "ERP → HubSpot - Mappers - Add technical mappings",
          optimistic: 1.0,
          pessimistic: 4.0,
          realistic: 2.5,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-8",
          label: "ERP → HubSpot - Producer - Setup producer",
          optimistic: 1.5,
          pessimistic: 4.5,
          realistic: 3.0,
        },
        {
          id: "es-4-erp-companies-hubspot-companies-9",
          label: "HubSpot - Event Webhook - Merge events",
          optimistic: 0.5,
          pessimistic: 1.5,
          realistic: 1.0,
        },
      ],
    },
    {
      id: "es-5-erp-contacts-hubspot-contacts",
      label: "ERP Contacts → HubSpot Contacts",
      included: false,
      items: [
        {
          id: "es-5-erp-contacts-hubspot-contacts-1",
          label: "Add API call to retrieve ERP contacts based on some criteria",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-2",
          label: "Create fields with custom ERP Contact property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-3",
          label: "Create fields with custom HubSpot Contact property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-4",
          label: "Add ‘HubSpot Relevant’ values",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-5",
          label: "ERP → HubSpot - Consumer - Add filter criteria",
          optimistic: 1.5,
          pessimistic: 3.0,
          realistic: 2.0,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-6",
          label: "ERP → HubSpot - Mappers - Add technical mappings",
          optimistic: 1.0,
          pessimistic: 4.0,
          realistic: 2.5,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-7",
          label: "ERP → HubSpot - Producer - Setup producer",
          optimistic: 1.5,
          pessimistic: 4.5,
          realistic: 3.0,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-8",
          label: "HubSpot - Event Webhook - Company association based on External Account ID",
          optimistic: 1.0,
          pessimistic: 2.0,
          realistic: 1.5,
        },
        {
          id: "es-5-erp-contacts-hubspot-contacts-9",
          label: "HubSpot - Event Webhook - Merge events",
          optimistic: 0.5,
          pessimistic: 1.5,
          realistic: 1.0,
        },
      ],
    },
    {
      id: "es-6-hubspot-contacts-erp-contacts",
      label: "HubSpot Contacts → ERP Contacts",
      included: false,
      items: [
        {
          id: "es-6-hubspot-contacts-erp-contacts-1",
          label: "Add API calls to create and update ERP contacts by ID",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-6-hubspot-contacts-erp-contacts-2",
          label: "HubSpot → ERP - Consumer - Configure List consumer",
          optimistic: 1.5,
          pessimistic: 3.0,
          realistic: 2.0,
        },
        {
          id: "es-6-hubspot-contacts-erp-contacts-3",
          label: "HubSpot → ERP - Mappers - Add technical mappings",
          optimistic: 1.0,
          pessimistic: 4.0,
          realistic: 2.5,
        },
        {
          id: "es-6-hubspot-contacts-erp-contacts-4",
          label: "HubSpot → ERP - Producer - Setup producer",
          optimistic: 2.0,
          pessimistic: 5.0,
          realistic: 3.5,
        },
      ],
    },
    {
      id: "es-7-erp-active-leads-hubspot-contacts",
      label: "ERP Active Leads → HubSpot Contacts",
      included: true,
      items: [
        {
          id: "es-7-erp-active-leads-hubspot-contacts-1",
          label: "Add API call to retrieve ERP leads based on some criteria",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-2",
          label: "Create fields with custom ERP Lead property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-3",
          label: "Create fields with custom HubSpot Lead property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-4",
          label: "Add ‘HubSpot Relevant’ values",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-5",
          label: "Active Leads - ERP → HubSpot - Consumer - Add filter criteria",
          optimistic: 1.5,
          pessimistic: 2.5,
          realistic: 2.0,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-6",
          label: "Active Leads - ERP → HubSpot - Webhook - Create webhook",
          optimistic: 1.0,
          pessimistic: 3.0,
          realistic: 1.5,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-7",
          label: "Active Leads - ERP → HubSpot - Mappers - Add technical mappings",
          optimistic: 1.0,
          pessimistic: 4.0,
          realistic: 2.5,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-8",
          label: "Active Leads - ERP → HubSpot - Producer - Setup producer",
          optimistic: 1.5,
          pessimistic: 4.5,
          realistic: 3.0,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-9",
          label: "Active Leads - HubSpot - Event Webhook - Company association based on External Account ID",
          optimistic: 1.0,
          pessimistic: 2.0,
          realistic: 1.5,
        },
        {
          id: "es-7-erp-active-leads-hubspot-contacts-10",
          label: "Active Leads - HubSpot - Event Webhook - Contact association based on External Contact ID",
          optimistic: 1.0,
          pessimistic: 2.0,
          realistic: 1.5,
        },
      ],
    },
    {
      id: "es-8-hubspot-contacts-erp-active-leads",
      label: "HubSpot Contacts → ERP Active Leads",
      included: true,
      items: [
        {
          id: "es-8-hubspot-contacts-erp-active-leads-1",
          label: "Add API calls to create and update ERP leads by ID",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-8-hubspot-contacts-erp-active-leads-2",
          label: "Active Leads - HubSpot → ERP - Consumer - Configure List consumer",
          optimistic: 2.0,
          pessimistic: 4.0,
          realistic: 3.0,
        },
        {
          id: "es-8-hubspot-contacts-erp-active-leads-3",
          label: "Active Leads - HubSpot → ERP - Workflow Webhook - Create webhook",
          optimistic: 1.5,
          pessimistic: 3.0,
          realistic: 2.5,
        },
        {
          id: "es-8-hubspot-contacts-erp-active-leads-4",
          label: "Active Leads - HubSpot → ERP - Mappers - Add technical mappings",
          optimistic: 1.0,
          pessimistic: 4.0,
          realistic: 2.5,
        },
        {
          id: "es-8-hubspot-contacts-erp-active-leads-5",
          label: "Active Leads - HubSpot → ERP - Producer - Setup producer",
          optimistic: 2.0,
          pessimistic: 5.0,
          realistic: 3.5,
        },
      ],
    },
    {
      id: "es-9-erp-inactive-leads-hubspot-contacts",
      label: "ERP Inactive Leads → HubSpot Contacts",
      included: true,
      items: [
        {
          id: "es-9-erp-inactive-leads-hubspot-contacts-1",
          label: "Inactive Leads - ERP → HubSpot - Consumer - Add filter criteria",
          optimistic: 1.5,
          pessimistic: 2.5,
          realistic: 2.0,
        },
        {
          id: "es-9-erp-inactive-leads-hubspot-contacts-2",
          label: "Inactive Leads - ERP → HubSpot - Deactivate in SyncDB",
          optimistic: 1.0,
          pessimistic: 1.5,
          realistic: 1.25,
        },
        {
          id: "es-9-erp-inactive-leads-hubspot-contacts-3",
          label: "Inactive Leads - ERP → HubSpot - Update in ERP",
          optimistic: 2.0,
          pessimistic: 3.0,
          realistic: 2.5,
        },
        {
          id: "es-9-erp-inactive-leads-hubspot-contacts-4",
          label: "Inactive Leads - ERP → HubSpot - Update HubSpot external entity",
          optimistic: 2.0,
          pessimistic: 3.0,
          realistic: 2.5,
        },
      ],
    },
    {
      id: "es-10-erp-opportunities-hubspot-deals",
      label: "ERP Opportunities → HubSpot Deals",
      included: false,
      items: [
        {
          id: "es-10-erp-opportunities-hubspot-deals-1",
          label: "Add API call to retrieve ERP opportunities based on some criteria",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-2",
          label: "Create fields with custom ERP Opportunity property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-3",
          label: "Create fields with custom HubSpot Deal property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-4",
          label: "Add ‘HubSpot relevant’ values",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-5",
          label: "Configure environmental IDs (deal stages, pipeline IDs,..)",
          optimistic: 0.5,
          pessimistic: 1.0,
          realistic: 0.75,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-6",
          label: "ERP → HubSpot - Consumer - Add filter criteria",
          optimistic: 1.5,
          pessimistic: 2.5,
          realistic: 2.0,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-7",
          label: "ERP → HubSpot - Mappers - Add technical mappings",
          optimistic: 1.0,
          pessimistic: 4.0,
          realistic: 2.5,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-8",
          label: "ERP → HubSpot - Producer - Setup producer",
          optimistic: 2.0,
          pessimistic: 5.0,
          realistic: 3.5,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-9",
          label: "HubSpot - Event Webhook - Company association based on External Account ID",
          optimistic: 1.0,
          pessimistic: 2.0,
          realistic: 1.5,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-10",
          label: "HubSpot - Event Webhook - Contact association based on External Contact ID",
          optimistic: 1.0,
          pessimistic: 2.0,
          realistic: 1.5,
        },
        {
          id: "es-10-erp-opportunities-hubspot-deals-11",
          label: "HubSpot - Event Webhook - Merge events",
          optimistic: 0.5,
          pessimistic: 1.5,
          realistic: 1.0,
        },
      ],
    },
    {
      id: "es-11-erp-line-items-hubspot-line-items",
      label: "ERP Line Items → HubSpot Line Items",
      included: false,
      items: [
        {
          id: "es-11-erp-line-items-hubspot-line-items-1",
          label: "Add API call to retrieve ERP line items based on Opportunity ID (unless included with Opportunities)",
          optimistic: 0.25,
          pessimistic: 0.5,
          realistic: 0.25,
        },
        {
          id: "es-11-erp-line-items-hubspot-line-items-2",
          label: "Create fields with custom ERP Line Item property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-11-erp-line-items-hubspot-line-items-3",
          label: "Create fields with custom HubSpot Line Item property names",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-11-erp-line-items-hubspot-line-items-4",
          label: "ERP → HubSpot - Consumer - Consume based on previously synced opportunity IDs (unless Line Items included with Opportunities sync)",
          optimistic: 3.0,
          pessimistic: 9.0,
          realistic: 6.0,
        },
        {
          id: "es-11-erp-line-items-hubspot-line-items-5",
          label: "ERP → HubSpot - Mappers - Add technical mappings",
          optimistic: 1.5,
          pessimistic: 5.0,
          realistic: 3.5,
        },
        {
          id: "es-11-erp-line-items-hubspot-line-items-6",
          label: "ERP → HubSpot - Producer - Setup producer",
          optimistic: 2.0,
          pessimistic: 5.0,
          realistic: 3.5,
        },
        {
          id: "es-11-erp-line-items-hubspot-line-items-7",
          label: "HubSpot - Event Webhook - Deal association based on External Opportunity ID",
          optimistic: 1.0,
          pessimistic: 2.0,
          realistic: 1.5,
        },
      ],
    },
    {
      id: "es-12-erp-custom-object-hubspot-custom-object",
      label: "ERP Custom Object → HubSpot Custom Object",
      included: false,
      items: [
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-1",
          label: "Add API call to retrieve CRM/ERP Object based on some criteria",
          optimistic: 0.5,
          pessimistic: 1.0,
          realistic: 0.75,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-2",
          label: "Add API calls to create and update CRM/ERP Object",
          optimistic: 0.5,
          pessimistic: 1.0,
          realistic: 0.75,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-3",
          label: "Create fields wit custom CRM/ERP Object property names",
          optimistic: 1.0,
          pessimistic: 2.5,
          realistic: 1.5,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-4",
          label: "Create fields wit custom Hubspot Object property names",
          optimistic: 1.0,
          pessimistic: 2.5,
          realistic: 1.5,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-5",
          label: "Configure Hubspot Custom Object ID for eac environment",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-6",
          label: "Add ‘Hubspot Relevant’ values",
          optimistic: 0.25,
          pessimistic: 1.0,
          realistic: 0.5,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-7",
          label: "CRM/ERP → Hubspot - Consumer - Add filter criteria",
          optimistic: 3.0,
          pessimistic: 9.0,
          realistic: 6.0,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-8",
          label: "CRM/ERP → Hubspot - Mappers - Add tecnical mappings",
          optimistic: 2.5,
          pessimistic: 6.0,
          realistic: 4.5,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-9",
          label: "CRM/ERP → Hubspot - Producer - Setup producer",
          optimistic: 2.0,
          pessimistic: 5.0,
          realistic: 3.5,
        },
        {
          id: "es-12-erp-custom-object-hubspot-custom-object-10",
          label: "Hubspot - Workflow Webook - Associations (per association)",
          optimistic: 6.0,
          pessimistic: 10.0,
          realistic: 8.0,
        },
      ],
    },
  ],
  subscriptionQty: 0,
  subscriptionUnitPrice: 5000,
};

export const DEFAULT_PM_RATE = 175;
export const DEFAULT_PM_PERCENT = 0.15;

export function createDefaultEstimationState(): EstimationState {
  return {
    standardWorkstreams: structuredClone(STANDARD_WORKSTREAM_TEMPLATES),
    thirdPartyIntegration: structuredClone(THIRD_PARTY_INTEGRATION_TEMPLATE),
    elixirSyncIntegration: structuredClone(ELIXIRSYNC_INTEGRATION_TEMPLATE),
    pmRate: DEFAULT_PM_RATE,
    pmPercent: DEFAULT_PM_PERCENT,
  };
}
